import type { Exercise } from '../types';

/**
 * Semilla de ejercicios originales (la meta de la primera versión es 20 a 30, con una animación por patrón de movimiento).
 * Los textos son orientativos; antes de publicar los revisa un profesional del deporte.
 */
export const EXERCISES: readonly Exercise[] = [
  {
    id: 'sentadilla-peso-corporal',
    name: 'Sentadilla con peso corporal',
    category: 'fuerza',
    pattern: 'sentadilla',
    steps: ['Pies al ancho de los hombros, puntas ligeramente hacia fuera.', 'Baja llevando la cadera atrás y abajo, con el pecho alto.', 'Mantén las rodillas en línea con los pies.', 'Sube empujando el suelo con todo el pie.'],
    commonMistake: 'Dejar que las rodillas se cierren hacia dentro al subir.',
    sets: 3, reps: 12, seconds: null, restSeconds: 45,
    equipment: ['ninguno'], loadsZones: ['cuadriceps', 'rodilla', 'cadera'],
    youtubeQuery: 'sentadilla peso corporal técnica correcta',
  },
  {
    id: 'puente-gluteo',
    name: 'Puente de glúteo',
    category: 'fuerza',
    pattern: 'bisagra',
    steps: ['Tumbado boca arriba, rodillas dobladas y pies apoyados.', 'Aprieta los glúteos y eleva la cadera hasta formar una línea del hombro a la rodilla.', 'Pausa un segundo arriba sin arquear la espalda.', 'Baja controlando.'],
    commonMistake: 'Arquear la zona lumbar en lugar de usar los glúteos.',
    sets: 3, reps: 12, seconds: null, restSeconds: 40,
    equipment: ['ninguno'], loadsZones: ['cadera', 'isquiotibiales'],
    youtubeQuery: 'puente de glúteo técnica',
  },
  {
    id: 'zancada-alterna',
    name: 'Zancada alterna',
    category: 'fuerza',
    pattern: 'zancada',
    steps: ['Da un paso largo hacia delante.', 'Baja hasta que ambas rodillas formen unos 90 grados.', 'Empuja con la pierna de delante para volver.', 'Alterna de pierna.'],
    commonMistake: 'Pasos demasiado cortos que cargan de más la rodilla.',
    sets: 3, reps: 10, seconds: null, restSeconds: 45,
    equipment: ['ninguno'], loadsZones: ['rodilla', 'cuadriceps', 'cadera'],
    youtubeQuery: 'zancada alterna técnica',
  },
  {
    id: 'plancha-frontal',
    name: 'Plancha frontal',
    category: 'core',
    pattern: 'plancha',
    steps: ['Apóyate en antebrazos y puntas de los pies.', 'Alinea cabeza, espalda y piernas.', 'Aprieta abdomen y glúteos.', 'Respira de forma continua.'],
    commonMistake: 'Dejar caer la cadera o subirla demasiado.',
    sets: 3, reps: null, seconds: 30, restSeconds: 30,
    equipment: ['ninguno'], loadsZones: ['hombro', 'lumbar'],
    youtubeQuery: 'plancha frontal técnica',
  },
  {
    id: 'plancha-lateral',
    name: 'Plancha lateral',
    category: 'core',
    pattern: 'plancha',
    steps: ['De lado, apoya el antebrazo bajo el hombro.', 'Eleva la cadera hasta alinear el cuerpo.', 'Mantén sin girar el tronco.', 'Repite al otro lado.'],
    commonMistake: 'Girar el pecho hacia el suelo.',
    sets: 3, reps: null, seconds: 20, restSeconds: 30,
    equipment: ['ninguno'], loadsZones: ['hombro', 'lumbar'],
    youtubeQuery: 'plancha lateral técnica',
  },
  {
    id: 'nordic-asistido',
    name: 'Nordic asistido (isquiotibiales)',
    category: 'prevencion',
    pattern: 'bisagra',
    steps: ['De rodillas, con alguien o algo que sujete tus tobillos.', 'Mantén el cuerpo recto de rodillas a cabeza.', 'Inclínate hacia delante lo más lento que puedas.', 'Amortigua con las manos y empuja suave para volver.'],
    commonMistake: 'Doblar la cadera en lugar de mantener el cuerpo recto.',
    sets: 3, reps: 6, seconds: null, restSeconds: 60,
    equipment: ['ninguno'], loadsZones: ['isquiotibiales', 'rodilla'],
    youtubeQuery: 'nordic hamstring curl técnica principiantes',
  },
  {
    id: 'copenhagen-rodilla',
    name: 'Copenhagen con rodilla apoyada',
    category: 'prevencion',
    pattern: 'plancha',
    steps: ['En plancha lateral, apoya la rodilla de arriba sobre un banco o silla.', 'Eleva la cadera alineando el cuerpo.', 'Mantén el tiempo indicado.', 'Cambia de lado.'],
    commonMistake: 'Dejar caer la cadera hacia el suelo.',
    sets: 3, reps: null, seconds: 20, restSeconds: 40,
    equipment: ['ninguno'], loadsZones: ['ingle', 'cadera'],
    youtubeQuery: 'copenhagen plank aductores principiantes',
  },
  {
    id: 'equilibrio-unipodal',
    name: 'Equilibrio sobre una pierna',
    category: 'prevencion',
    pattern: 'equilibrio',
    steps: ['De pie sobre una pierna, rodilla ligeramente flexionada.', 'Mira al frente y mantén la cadera nivelada.', 'Aguanta el tiempo indicado.', 'Cambia de pierna.'],
    commonMistake: 'Bloquear la rodilla en extensión.',
    sets: 3, reps: null, seconds: 30, restSeconds: 20,
    equipment: ['ninguno'], loadsZones: ['tobillo', 'rodilla'],
    youtubeQuery: 'equilibrio unipodal ejercicios prevención lesiones tobillo',
  },
  {
    id: 'salto-aterrizaje',
    name: 'Salto con aterrizaje controlado',
    category: 'potencia',
    pattern: 'salto',
    steps: ['Pies al ancho de los hombros, flexiona caderas y rodillas.', 'Salta hacia arriba con intención.', 'Aterriza suave, en la punta y luego todo el pie, rodillas alineadas.', 'Mantén dos segundos antes de repetir.'],
    commonMistake: 'Aterrizar con las rodillas hacia dentro o con las piernas rígidas.',
    sets: 3, reps: 8, seconds: null, restSeconds: 60,
    equipment: ['ninguno'], loadsZones: ['rodilla', 'tobillo', 'gemelo'],
    youtubeQuery: 'saltos aterrizaje controlado prevención lesiones rodilla',
  },
  {
    id: 'skipping-alto',
    name: 'Skipping alto',
    category: 'calentamiento',
    pattern: 'carrera',
    steps: ['Sube las rodillas a la altura de la cadera.', 'Brazos coordinados con las piernas.', 'Contactos cortos y ligeros con el suelo.', 'Mantén el tronco erguido.'],
    commonMistake: 'Inclinarse hacia atrás.',
    sets: 3, reps: null, seconds: 20, restSeconds: 20,
    equipment: ['ninguno'], loadsZones: ['gemelo', 'tobillo'],
    youtubeQuery: 'skipping alto técnica de carrera',
  },
  {
    id: 'carrera-progresiva',
    name: 'Carrera progresiva de 20 m',
    category: 'velocidad',
    pattern: 'carrera',
    steps: ['Marca 20 metros.', 'Acelera de forma progresiva sin llegar al máximo al inicio.', 'Termina rápido pero relajado.', 'Camina de vuelta para recuperar.'],
    commonMistake: 'Salir al máximo desde el primer paso con el músculo frío.',
    sets: 6, reps: 1, seconds: null, restSeconds: 60,
    equipment: ['conos'], loadsZones: ['isquiotibiales', 'gemelo', 'aquiles'],
    youtubeQuery: 'carrera progresiva aceleración técnica',
  },
  {
    id: 'movilidad-cadera-90-90',
    name: 'Movilidad de cadera 90/90',
    category: 'movilidad',
    pattern: 'movilidad',
    steps: ['Sentado, una pierna delante y otra al lado, ambas a 90 grados.', 'Mantén la espalda larga.', 'Rota despacio hacia el otro lado.', 'Muévete sin dolor.'],
    commonMistake: 'Forzar el rango hasta sentir dolor.',
    sets: 2, reps: 10, seconds: null, restSeconds: 20,
    equipment: ['ninguno'], loadsZones: ['cadera'],
    youtubeQuery: 'movilidad de cadera 90 90',
  },
  {
    id: 'movilidad-tobillo-pared',
    name: 'Movilidad de tobillo en pared',
    category: 'movilidad',
    pattern: 'movilidad',
    steps: ['Pie a unos 10 cm de la pared.', 'Lleva la rodilla hacia la pared sin levantar el talón.', 'Vuelve y repite.', 'Cambia de pie.'],
    commonMistake: 'Levantar el talón del suelo.',
    sets: 2, reps: 10, seconds: null, restSeconds: 20,
    equipment: ['ninguno'], loadsZones: ['tobillo'],
    youtubeQuery: 'movilidad de tobillo en pared',
  },
  {
    id: 'toques-pared',
    name: 'Toques a la pared',
    category: 'tecnica',
    pattern: 'equilibrio',
    steps: ['A 2 metros de una pared.', 'Pasa el balón con el interior del pie y controla el rebote.', 'Alterna pie derecho e izquierdo.', 'Sube la velocidad poco a poco.'],
    commonMistake: 'Golpear sin controlar el primer toque.',
    sets: 3, reps: null, seconds: 40, restSeconds: 30,
    equipment: ['balon'], loadsZones: ['tobillo', 'pie'],
    youtubeQuery: 'ejercicios de control y pase contra la pared fútbol',
  },
  {
    id: 'escalera-agilidad',
    name: 'Escalera de agilidad: pasos rápidos',
    category: 'agilidad',
    pattern: 'carrera',
    steps: ['Un pie en cada cuadro, pasos cortos y rápidos.', 'Mira al frente, no a los pies.', 'Brazos activos.', 'Camina de vuelta.'],
    commonMistake: 'Pisar las líneas por ir demasiado rápido al inicio.',
    sets: 4, reps: 1, seconds: null, restSeconds: 30,
    equipment: ['escalera'], loadsZones: ['tobillo', 'gemelo'],
    youtubeQuery: 'escalera de agilidad ejercicios básicos',
  },
  {
    id: 'flexiones-rodillas',
    name: 'Flexiones con rodillas apoyadas',
    category: 'fuerza',
    pattern: 'empuje',
    steps: ['Manos bajo los hombros, rodillas apoyadas.', 'Cuerpo alineado de rodillas a cabeza.', 'Baja el pecho cerca del suelo.', 'Empuja hasta estirar los brazos.'],
    commonMistake: 'Dejar caer la cadera.',
    sets: 3, reps: 10, seconds: null, restSeconds: 45,
    equipment: ['ninguno'], loadsZones: ['hombro'],
    youtubeQuery: 'flexiones con rodillas apoyadas técnica',
  },
  {
    id: 'remo-banda',
    name: 'Remo con banda elástica',
    category: 'fuerza',
    pattern: 'tiron',
    steps: ['Sujeta la banda a un punto firme a la altura del pecho.', 'Tira hacia las costillas juntando los omóplatos.', 'Pausa un segundo.', 'Vuelve despacio.'],
    commonMistake: 'Encogerse de hombros al tirar.',
    sets: 3, reps: 12, seconds: null, restSeconds: 40,
    equipment: ['bandas'], loadsZones: ['hombro'],
    youtubeQuery: 'remo con banda elástica técnica',
  },
  {
    id: 'respiracion-calma',
    name: 'Respiración de vuelta a la calma',
    category: 'vueltaCalma',
    pattern: 'movilidad',
    steps: ['Siéntate o túmbate cómodo.', 'Inhala por la nariz contando cuatro.', 'Exhala despacio por la boca contando seis.', 'Repite durante dos minutos.'],
    commonMistake: 'Forzar la respiración hasta marearte.',
    sets: 1, reps: null, seconds: 120, restSeconds: 0,
    equipment: ['ninguno'], loadsZones: [],
    youtubeQuery: 'respiración para recuperación después de entrenar',
  },
  {
    id: 'peso-muerto-rumano-unipodal',
    name: 'Peso muerto rumano a una pierna',
    category: 'prevencion',
    pattern: 'bisagra',
    steps: ['De pie sobre una pierna con la rodilla ligeramente flexionada.', 'Inclina el tronco llevando la cadera atrás y la otra pierna extendida detrás.', 'Mantén la espalda recta hasta sentir tensión en la parte trasera del muslo.', 'Vuelve apretando el glúteo.'],
    commonMistake: 'Girar la cadera hacia un lado en lugar de mantenerla cuadrada.',
    sets: 3, reps: 8, seconds: null, restSeconds: 45,
    equipment: ['ninguno'], loadsZones: ['isquiotibiales', 'cadera', 'lumbar'],
    youtubeQuery: 'peso muerto rumano a una pierna técnica',
  },
  {
    id: 'sentadilla-bulgara',
    name: 'Sentadilla búlgara',
    category: 'fuerza',
    pattern: 'zancada',
    steps: ['Apoya el empeine de una pierna atrás, sobre un banco o sofá.', 'Baja recto con el tronco ligeramente inclinado.', 'La rodilla de delante sigue la línea del pie.', 'Sube empujando con el talón.'],
    commonMistake: 'Poner el pie delantero demasiado cerca del banco.',
    sets: 3, reps: 8, seconds: null, restSeconds: 60,
    equipment: ['ninguno'], loadsZones: ['rodilla', 'cuadriceps', 'cadera'],
    youtubeQuery: 'sentadilla búlgara técnica correcta',
  },
  {
    id: 'elevacion-gemelos',
    name: 'Elevación de gemelos',
    category: 'prevencion',
    pattern: 'empuje',
    steps: ['De pie en el borde de un escalón con los talones fuera.', 'Sube sobre las puntas de los pies lo más alto que puedas.', 'Baja despacio hasta sentir estirar el gemelo.', 'Haz la bajada en tres segundos.'],
    commonMistake: 'Rebotar sin controlar la bajada.',
    sets: 3, reps: 12, seconds: null, restSeconds: 40,
    equipment: ['ninguno'], loadsZones: ['gemelo', 'aquiles', 'tobillo'],
    youtubeQuery: 'elevación de gemelos para futbolistas',
  },
  {
    id: 'dead-bug',
    name: 'Bicho muerto (dead bug)',
    category: 'core',
    pattern: 'plancha',
    steps: ['Tumbado boca arriba con brazos al techo y rodillas a 90 grados.', 'Pega la zona lumbar al suelo.', 'Baja a la vez un brazo y la pierna contraria sin despegar la espalda.', 'Vuelve y alterna.'],
    commonMistake: 'Dejar que la espalda se arquee al bajar la pierna.',
    sets: 3, reps: 10, seconds: null, restSeconds: 30,
    equipment: ['ninguno'], loadsZones: [],
    youtubeQuery: 'dead bug ejercicio core técnica',
  },
  {
    id: 'pallof-banda',
    name: 'Press Pallof con banda',
    category: 'core',
    pattern: 'empuje',
    steps: ['De lado a un anclaje con la banda a la altura del pecho.', 'Lleva las manos al pecho y estira los brazos al frente.', 'Resiste el giro que intenta hacer la banda.', 'Vuelve lento al pecho.'],
    commonMistake: 'Dejar que el tronco rote hacia el anclaje.',
    sets: 3, reps: 10, seconds: null, restSeconds: 30,
    equipment: ['bandas'], loadsZones: [],
    youtubeQuery: 'press pallof con banda técnica',
  },
  {
    id: 'salto-cajon',
    name: 'Salto al cajón bajo',
    category: 'potencia',
    pattern: 'salto',
    steps: ['Frente a un escalón estable y bajo.', 'Flexiona rodillas y cadera, balancea los brazos.', 'Salta y aterriza con los dos pies, suave y silencioso.', 'Baja caminando, sin saltar hacia abajo.'],
    commonMistake: 'Aterrizar con las rodillas hacia dentro o rígido.',
    sets: 3, reps: 6, seconds: null, restSeconds: 60,
    equipment: ['ninguno'], loadsZones: ['rodilla', 'tobillo', 'cuadriceps'],
    youtubeQuery: 'salto al cajón técnica aterrizaje',
  },
  {
    id: 'sprint-30m',
    name: 'Sprints de 30 metros',
    category: 'velocidad',
    pattern: 'carrera',
    steps: ['Calienta bien antes: trote y progresiones.', 'Salida con inclinación del cuerpo hacia delante.', 'Acelera al máximo y mantén la técnica.', 'Camina de vuelta para recuperar.'],
    commonMistake: 'Hacerlo con el cuerpo frío o sin descanso suficiente.',
    sets: 6, reps: 1, seconds: null, restSeconds: 90,
    equipment: ['conos'], loadsZones: ['isquiotibiales', 'cuadriceps', 'gemelo', 'aquiles'],
    youtubeQuery: 'técnica de sprint 30 metros fútbol',
  },
  {
    id: 'cambio-direccion-t',
    name: 'Test en T de cambio de dirección',
    category: 'agilidad',
    pattern: 'carrera',
    steps: ['Coloca cuatro conos en forma de T con 5 metros entre ellos.', 'Corre al frente, desplázate lateral a cada lado y vuelve de espaldas.', 'Baja el centro de gravedad en cada giro.', 'Descansa y repite.'],
    commonMistake: 'Girar con las piernas rígidas y el cuerpo erguido.',
    sets: 4, reps: 1, seconds: null, restSeconds: 75,
    equipment: ['conos'], loadsZones: ['rodilla', 'tobillo', 'cadera'],
    youtubeQuery: 'ejercicio agilidad en T conos fútbol',
  },
  {
    id: 'conduccion-conos',
    name: 'Conducción de balón entre conos',
    category: 'tecnica',
    pattern: 'carrera',
    steps: ['Coloca 6 conos en línea separados 1,5 metros.', 'Conduce el balón con el interior y el exterior del pie.', 'Mantén la cabeza alta de vez en cuando.', 'Repite con la pierna menos hábil.'],
    commonMistake: 'Mirar solo el balón todo el tiempo.',
    sets: 4, reps: 1, seconds: null, restSeconds: 45,
    equipment: ['balon', 'conos'], loadsZones: ['tobillo'],
    youtubeQuery: 'conducción de balón entre conos ejercicios',
  },
  {
    id: 'pase-pared-dos-toques',
    name: 'Pases a la pared a dos toques',
    category: 'tecnica',
    pattern: 'equilibrio',
    steps: ['A 3 metros de una pared firme.', 'Controla con un toque y pasa con el segundo.', 'Alterna el pie derecho y el izquierdo.', 'Acelera sin perder la precisión.'],
    commonMistake: 'Golpear con la punta en lugar del interior del pie.',
    sets: 3, reps: 20, seconds: null, restSeconds: 30,
    equipment: ['balon'], loadsZones: [],
    youtubeQuery: 'pases a la pared fútbol técnica',
  },
  {
    id: 'movilidad-cuello-hombros',
    name: 'Movilidad de hombros y cuello',
    category: 'movilidad',
    pattern: 'movilidad',
    steps: ['Haz círculos amplios con los hombros hacia atrás.', 'Inclina el cuello suavemente a cada lado sin forzar.', 'Abre y cierra los brazos con la espalda recta.', 'Respira con calma durante todo el ejercicio.'],
    commonMistake: 'Forzar el cuello hasta sentir tirón.',
    sets: 1, reps: null, seconds: 90, restSeconds: 0,
    equipment: ['ninguno'], loadsZones: [],
    youtubeQuery: 'movilidad de hombros y cuello rutina',
  },
  {
    id: 'foam-roller-piernas',
    name: 'Liberación con rodillo de piernas',
    category: 'recuperacion',
    pattern: 'movilidad',
    steps: ['Apoya el muslo sobre el rodillo (o una botella dura).', 'Desplázate despacio de la cadera a la rodilla.', 'Detente 20 segundos en un punto sensible, sin dolor agudo.', 'Cambia a gemelos y vuelve.'],
    commonMistake: 'Pasar el rodillo directo sobre la rodilla o sobre una zona lesionada.',
    sets: 1, reps: null, seconds: 180, restSeconds: 0,
    equipment: ['ninguno'], loadsZones: [],
    youtubeQuery: 'foam roller piernas recuperación fútbol',
  },
];

export const EXERCISE_BY_ID: ReadonlyMap<string, Exercise> = new Map(EXERCISES.map((e) => [e.id, e]));

export function youtubeSearchUrl(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}
